[package]
name = "lambda-network-monitor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
ctor = "0.2"
once_cell = "1.20"
simple_logger= { version = "5.0.0", default-features = false}
log = "0.4.25"

